class Article {
  final String text;
  final String domain;
  final String by;
  final String age;
  final int score;
  final int commentCount;

  const Article({
    this.text,
    this.domain,
    this.by,
    this.age,
    this.score,
    this.commentCount});
}

final articles = [
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
  new Article(
    text: 'Circular Shock Acoustic waves found!',
    domain: 'wiley.com',
    by: 'zdw',
    age: '3 hours',
    score: 12,
    commentCount: 4,
  ),
];